#specifies the version og the compose file format
version: '3'
name: mapappproject

#defines the contiainers that will be started as part of the docker
#compose instance. Each service represent a container and includes various config options
services:
  web:
    image: mapapp
    ports: 
      - "80:80"
    depends_on:
      - server

  server:
    image: mapserver
    ports: 
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data:/usr/src/app/data

